"""add flashcard fields to note

Revision ID: c77185562f94
Revises: 02c0271fa35f
Create Date: 2025-06-21 14:48:41.576583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77185562f94'
down_revision = '02c0271fa35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flashcard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('front_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('back_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('back_content')
        batch_op.drop_column('front_content')
        batch_op.drop_column('is_flashcard')

    # ### end Alembic commands ###
